# Generated by Django 4.1.4 on 2022-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadDocuments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='firstname',
            field=models.CharField(blank=True, default='firstname', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='lastname',
            field=models.CharField(blank=True, default='lastname', max_length=50, null=True),
        ),
    ]
