# Generated by Django 4.1.4 on 2022-12-25 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadDocuments', '0005_pdfdocument_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
