# Generated by Django 4.1.4 on 2022-12-25 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadDocuments', '0006_alter_pdfdocument_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='JpgDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/jpg')),
                ('text', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jpgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
